### PR TITLE
🔴 [fixes] update and remove bugs from original.css 

### PR DESCRIPTION
**Pull request by ankushchk**
**I fixes the google import url, the font-family and prettier the text using vscode prettier extension .**

**Merge it !!!!!!**

### CODE REVIEW

**Comment by ankushchk** [comment]
.........

**Comment by ankushchk** [comment]
@jonmarkgo  @theycallmeswift  @nquinlan @bih please review !!!!

**Comment by nquinlan** [comment]
@An-prog-hub This seems to mostly change styles to no longer meet our CSS guidelines. Can you please explain the bug fixes?

**Comment by ankushchk** [comment]
importpoppins pg
- [x] Added "sans-serif" to the font-family which help to allocate the font from the googlefontapis.
- [x] Prevent the page from hungry reloading

<hr />

sans-serif
css2

Google Fonts have New CSS API update in which the starts with a new base URL : fonts.googleapis.com/**css2**
The syntax for specifying styles within each family has changed to describe variable font ‘design spaces.’

for more details visit -> https://developers.google.com/fonts/docs/css2

**Comment by ankushchk** [comment]
@nquinlan please review !!!

**Comment by nquinlan** [comment]
@An-prog-hub Thanks for the additional information.

I'd support a paired down pull-request that made only the two changes you described, rather than the other code style changes. If you'll make the updates, I'd be happy to merge.

I really appreciate you being excited to make these changes! However, it does take me and/or my team a little bit of time to do things like review GitHub PRs, so you might not get an answer within a day and I know we'd all really appreciate your patience as we do the reviews. I know how frustrating it can be to put work into a PR and not have the maintainer look at it-- frankly it sucks. I want to make sure that doesn't happen for you, but it would mean a lot if you'd give us just a little more time to review the PRs before tagging folks.

**Pull request closed without merging**
